### PR TITLE
Apply new design to samples

### PR DESCRIPTION
**Pull request by TsvetinaIvanova**

### CODE REVIEW

**Comment by didiepetrova** [comment]
Works good. Just two points: .debug.abproject and .release.abproject should not be included. Should the Note: be at the bottom as subfooter and not as a content?

**Comment by TsvetinaIvanova** [comment]
Removed  .debug.abproject and .release.abproject, moved the note to the subfooter and applied DisallowOverscroll=true in config.

**Comment by didiepetrova** [comment]
:+1:

**Comment by Mike4o** [comment]
:+1:

**Pull request merged**
